version: '3.8'

services:
  nestjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: localhost  # Use localhost to connect to MySQL running on host
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: stundents

  # Remove the MySQL service since we're using localhost
