version: '3.8'

services:
  nestjs:
    build: .
    ports:
      - "3002:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: students  # Nom corrigé
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672  # URL corrigée
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    entrypoint: ["dockerize", "-wait", "tcp://db:3306", "-wait", "tcp://rabbitmq:5672", "-timeout", "60s", "npm", "run", "start:dev"]  # Port corrigé

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: students  # Nom corrigé
    ports:
      - "3307:3306"
    networks:
      - app-network
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]  # Healthcheck corrigé
      interval: 10s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"   # Port AMQP pour la communication entre services
      - "15673:15672" # Interface Web de gestion RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local